spring.application.name: product

#server:
#    port: 8083


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761//eureka
    #puerto dinamico
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
    port: ${PORT:0}

#zipkin aumenta al 100% la probabilidad de enviar la traza zipkin
spring:
    sleuth:
        sampler:
            probability: 1.0
#configurar el endpoint del servidor zipkin
    zipkin:
        base-url: http://127.0.0.1:9411/
